// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXoCt0LoL5NBKF8c8oGSX-I5O_2YGlwyc',
    appId: '1:320471382990:web:cdb7288347f09618ec099f',
    messagingSenderId: '320471382990',
    projectId: 'amaltrack2026',
    authDomain: 'amaltrack2026.firebaseapp.com',
    storageBucket: 'amaltrack2026.firebasestorage.app',
    measurementId: 'G-X20VEEWT6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPHvr1Diywn902OeTHWLygIMy6qnnCw_A',
    appId: '1:320471382990:android:f14476916b074682ec099f',
    messagingSenderId: '320471382990',
    projectId: 'amaltrack2026',
    storageBucket: 'amaltrack2026.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy1x4IdZ1FmTYGCGHh_sj_XXKMWaGWJtA',
    appId: '1:320471382990:ios:6fc90803f37da798ec099f',
    messagingSenderId: '320471382990',
    projectId: 'amaltrack2026',
    storageBucket: 'amaltrack2026.firebasestorage.app',
    iosBundleId: 'com.amaltracker.amalTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXoCt0LoL5NBKF8c8oGSX-I5O_2YGlwyc',
    appId: '1:320471382990:web:58eef377f76698f5ec099f',
    messagingSenderId: '320471382990',
    projectId: 'amaltrack2026',
    authDomain: 'amaltrack2026.firebaseapp.com',
    storageBucket: 'amaltrack2026.firebasestorage.app',
    measurementId: 'G-8H9R6WW1V4',
  );
}
